TRUE: "true"
FALSE: "false"
NULL: "null"

?start: value
?value: object
      | array
      | string
      | SIGNED_NUMBER      -> number
      | TRUE               -> true
      | FALSE            -> false
      | NULL            -> null
array  : "[" [value ("," value)*] "]"
object : "{" [pair ("," pair)*] "}"
pair   : string ":" value
string : ESCAPED_STRING
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS